# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectosSiga',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('annio_meta', models.CharField(blank=True, db_column='annio_meta', max_length=4, null=True)),
                ('codi_meta', models.CharField(blank=True, db_column='codi_meta', max_length=4, null=True)),
                ('cod_proyecto', models.CharField(blank=True, db_column='cod_proyecto', max_length=4, null=True)),
                ('desc_proyecto', models.CharField(blank=True, db_column='desc_proyecto', max_length=255, null=True)),
                ('CODI_DEPE_TDE', models.CharField(blank=True, db_column='CODI_DEPE_TDE', max_length=4, null=True)),
                ('codi_depe_apro', models.CharField(blank=True, db_column='codi_depe_apro', max_length=4, null=True)),
                ('sigla', models.CharField(blank=True, db_column='sigla', max_length=50, null=True)),
            ],
            options={
                'db_table': 'proyectos_siga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=100)),
                ('usr_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_creacion', models.DateTimeField(blank=True, null=True)),
                ('usr_edicion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_edicion', models.DateTimeField(blank=True, null=True)),
                ('template_html', models.CharField(max_length=255, null=True)),
                ('is_padre', models.IntegerField(default=0)),
                ('icon', models.CharField(default='icon-home4', max_length=255)),
                ('modulo_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulos_hijos', to='proyectos.Modulo')),
            ],
            options={
                'db_table': 'MODULO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModuloRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_creacion', models.DateTimeField(blank=True, null=True)),
                ('usr_edicion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_edicion', models.DateTimeField(blank=True, null=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Modulo')),
            ],
            options={
                'db_table': 'MODULO_ROL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModuloRolPermisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_creacion', models.DateTimeField(blank=True, null=True)),
                ('usr_edicion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_edicion', models.DateTimeField(blank=True, null=True)),
                ('modulorol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.ModuloRol')),
            ],
            options={
                'db_table': 'MODULO_ROL_PERMISOS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('codigo', models.IntegerField()),
                ('dom_name_sufijo', models.CharField(max_length=100)),
                ('usr_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_creacion', models.DateTimeField(blank=True, null=True)),
                ('usr_edicion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_edicion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PERMISO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_siga', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(blank=True, max_length=50, null=True)),
                ('anio', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cod_meta', models.CharField(max_length=8)),
                ('estado', models.IntegerField(default=1)),
                ('usr_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_creacion', models.DateTimeField(blank=True, null=True)),
                ('usr_edicion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_edicion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PROYECTO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProyectoSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_base', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('servidor_bd', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_bd', models.CharField(blank=True, max_length=100, null=True)),
                ('url_receive', models.CharField(blank=True, max_length=100, null=True)),
                ('presentacion_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('presentacion_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('usr_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_creacion', models.DateTimeField(blank=True, null=True)),
                ('usr_edicion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_edicion', models.DateTimeField(blank=True, null=True)),
                ('presentation_image', models.CharField(blank=True, max_length=255, null=True)),
                ('proyectos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyecto')),
                ('sistemas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.Sistema')),
            ],
            options={
                'db_table': 'PROYECTO_SISTEMA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('codigo', models.CharField(blank=True, max_length=8, null=True)),
                ('usr_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_creacion', models.DateTimeField(blank=True, null=True)),
                ('usr_edicion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_edicion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ROL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('usr_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_creacion', models.DateTimeField(blank=True, null=True)),
                ('usr_edicion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_edicion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TIPO_USUARIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
                ('ape_pat', models.CharField(blank=True, max_length=50, null=True)),
                ('ape_mat', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_contrato_inicio', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_contrato_extended', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_contrato_fin', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('email_inst', models.CharField(blank=True, max_length=100, null=True)),
                ('email_personal', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=100)),
                ('usr_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_creacion', models.DateTimeField(blank=True, null=True)),
                ('usr_edicion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_edicion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.IntegerField(default=1)),
                ('ccdd', models.CharField(blank=True, max_length=2, null=True)),
                ('ccpp', models.CharField(blank=True, max_length=2, null=True)),
                ('ccdi', models.CharField(blank=True, max_length=2, null=True)),
                ('zona', models.CharField(blank=True, max_length=5, null=True)),
                ('rol', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Rol')),
                ('tipousuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.TipoUsuario')),
            ],
            options={
                'db_table': 'USUARIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuariosOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('navegador_detalle', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Usuario')),
            ],
            options={
                'db_table': 'USUARIO_ONLINE',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='sistemas',
            field=models.ManyToManyField(through='proyectos.ProyectoSistema', to='sistemas.Sistema'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='proyectosistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.ProyectoSistema'),
        ),
        migrations.AddField(
            model_name='modulorolpermisos',
            name='permisos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Permiso'),
        ),
        migrations.AddField(
            model_name='modulorol',
            name='permisos',
            field=models.ManyToManyField(through='proyectos.ModuloRolPermisos', to='proyectos.Permiso'),
        ),
        migrations.AddField(
            model_name='modulorol',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulo_rol', to='proyectos.Rol'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='proyectosistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.ProyectoSistema'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='roles',
            field=models.ManyToManyField(through='proyectos.ModuloRol', to='proyectos.Rol'),
        ),
        migrations.AlterUniqueTogether(
            name='usuario',
            unique_together=set([('usuario',)]),
        ),
        migrations.AlterUniqueTogether(
            name='proyectosistema',
            unique_together=set([('proyectos', 'sistemas')]),
        ),
        migrations.AlterUniqueTogether(
            name='proyecto',
            unique_together=set([('id_siga',)]),
        ),
        migrations.AlterUniqueTogether(
            name='modulorolpermisos',
            unique_together=set([('modulorol', 'permisos')]),
        ),
        migrations.AlterUniqueTogether(
            name='modulorol',
            unique_together=set([('rol', 'modulo')]),
        ),
    ]
