# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyectosistema_presentation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectosistema',
            name='presentation_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
