# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20170518_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
