# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20170502_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectosistema',
            name='url_receive',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
