# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_auto_20170522_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
