# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0004_webserviceparameters_parameterexample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webserviceparameters',
            name='parameterexample',
        ),
        migrations.AddField(
            model_name='parameter',
            name='parameterexample',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
