# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_contrato_extended',
            field=models.DateField(blank=True, null=True),
        ),
    ]
