# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_modulo', '0004_auto_20170119_2304'),
        ('usuario', '0002_auto_20170119_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloRolPermisosUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_creacion', models.DateTimeField(blank=True, null=True)),
                ('usr_edicion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_edicion', models.DateTimeField(blank=True, null=True)),
                ('modulorolpermisos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario_modulo.ModuloRolPermisos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
            options={
                'managed': True,
                'db_table': 'MODULO_ROL_PERMISOS_USUARIO',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='modulorolpermisousuario',
            field=models.ManyToManyField(related_name='modulorolpermisousuario', through='usuario.ModuloRolPermisosUsuario', to='usuario_modulo.ModuloRolPermisos'),
        ),
        migrations.AlterUniqueTogether(
            name='modulorolpermisosusuario',
            unique_together=set([('usuario', 'modulorolpermisos')]),
        ),
    ]
