# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20170119_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.IntegerField(default=1),
        ),
    ]
