# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_contrato_extended',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_contrato_fin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_contrato_inicio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
