# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20170306_1744'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuario',
            unique_together=set([('usuario',)]),
        ),
    ]
