# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_modulo', '0015_auto_20170227_0045'),
        ('usuario', '0007_auto_20170306_1813'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modulorolpermisosusuario',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='modulorolpermisosusuario',
            name='modulorolpermisos',
        ),
        migrations.RemoveField(
            model_name='modulorolpermisosusuario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='modulorolpermisousuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario_modulo.Rol'),
        ),
        migrations.DeleteModel(
            name='ModuloRolPermisosUsuario',
        ),
    ]
