# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20170307_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ccdd',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ccdi',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ccpp',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='zona',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
