# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=100)),
                ('usr_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_creacion', models.DateTimeField(blank=True, null=True)),
                ('usr_edicion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_edicion', models.DateTimeField(blank=True, null=True)),
                ('template_html', models.CharField(max_length=255, null=True)),
                ('is_padre', models.IntegerField(default=0)),
                ('icon', models.CharField(default='icon-home4', max_length=255)),
                ('modulo_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulos_hijos', to='usuario_modulo.Modulo')),
                ('proyectosistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.ProyectoSistema')),
            ],
            options={
                'managed': True,
                'db_table': 'MODULO',
            },
        ),
        migrations.CreateModel(
            name='ModuloRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_creacion', models.DateTimeField(blank=True, null=True)),
                ('usr_edicion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_edicion', models.DateTimeField(blank=True, null=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario_modulo.Modulo')),
            ],
            options={
                'managed': True,
                'db_table': 'MODULO_ROL',
            },
        ),
        migrations.CreateModel(
            name='ModuloRolPermisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_creacion', models.DateTimeField(blank=True, null=True)),
                ('usr_edicion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_edicion', models.DateTimeField(blank=True, null=True)),
                ('modulorol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario_modulo.ModuloRol')),
            ],
            options={
                'managed': True,
                'db_table': 'MODULO_ROL_PERMISOS',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('codigo', models.IntegerField()),
                ('dom_name_sufijo', models.CharField(max_length=100)),
                ('usr_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_creacion', models.DateTimeField(blank=True, null=True)),
                ('usr_edicion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_edicion', models.DateTimeField(blank=True, null=True)),
                ('proyectosistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.ProyectoSistema')),
            ],
            options={
                'managed': True,
                'db_table': 'PERMISO',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('codigo', models.CharField(blank=True, max_length=8, null=True)),
                ('usr_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_creacion', models.DateTimeField(blank=True, null=True)),
                ('usr_edicion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_edicion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'ROL',
            },
        ),
        migrations.AddField(
            model_name='modulorolpermisos',
            name='permisos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario_modulo.Permiso'),
        ),
        migrations.AddField(
            model_name='modulorol',
            name='permisos',
            field=models.ManyToManyField(through='usuario_modulo.ModuloRolPermisos', to='usuario_modulo.Permiso'),
        ),
        migrations.AddField(
            model_name='modulorol',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulo_rol', to='usuario_modulo.Rol'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='roles',
            field=models.ManyToManyField(through='usuario_modulo.ModuloRol', to='usuario_modulo.Rol'),
        ),
        migrations.AlterUniqueTogether(
            name='modulorolpermisos',
            unique_together=set([('modulorol', 'permisos')]),
        ),
        migrations.AlterUniqueTogether(
            name='modulorol',
            unique_together=set([('rol', 'modulo')]),
        ),
    ]
