# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_modulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='modulo_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario_modulo.Modulo'),
        ),
    ]
