# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20170119_1849'),
        ('usuario_modulo', '0002_auto_20170119_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_creacion', models.DateTimeField(blank=True, null=True)),
                ('usr_edicion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_edicion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MODULO_ROL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModuloRolPermisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_creacion', models.DateTimeField(blank=True, null=True)),
                ('usr_edicion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_edicion', models.DateTimeField(blank=True, null=True)),
                ('modulorol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario_modulo.ModuloRol')),
                ('permisos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario_modulo.Permiso')),
            ],
            options={
                'db_table': 'MODULO_ROL_PERMISOS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModuloRolPermisosUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_creacion', models.DateTimeField(blank=True, null=True)),
                ('usr_edicion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_edicion', models.DateTimeField(blank=True, null=True)),
                ('modulorolpermisos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario_modulo.ModuloRolPermisos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
            options={
                'db_table': 'MODULO_ROL_PERMISOS_USUARIO',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='modulopermiso',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='modulopermiso',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='modulopermiso',
            name='permiso',
        ),
        migrations.RemoveField(
            model_name='modulopermiso',
            name='roles',
        ),
        migrations.AlterUniqueTogether(
            name='modulopermisorol',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='modulopermisorol',
            name='modulopermiso',
        ),
        migrations.RemoveField(
            model_name='modulopermisorol',
            name='rol',
        ),
        migrations.AlterUniqueTogether(
            name='modulopermisorolusuario',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='modulopermisorolusuario',
            name='modulopermisorol',
        ),
        migrations.RemoveField(
            model_name='modulopermisorolusuario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='permisos',
        ),
        migrations.DeleteModel(
            name='ModuloPermiso',
        ),
        migrations.DeleteModel(
            name='ModuloPermisoRol',
        ),
        migrations.DeleteModel(
            name='ModuloPermisoRolUsuario',
        ),
        migrations.AddField(
            model_name='modulorol',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario_modulo.Modulo'),
        ),
        migrations.AddField(
            model_name='modulorol',
            name='permisos',
            field=models.ManyToManyField(through='usuario_modulo.ModuloRolPermisos', to='usuario_modulo.Permiso'),
        ),
        migrations.AddField(
            model_name='modulorol',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario_modulo.Rol'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='roles',
            field=models.ManyToManyField(through='usuario_modulo.ModuloRol', to='usuario_modulo.Rol'),
        ),
        migrations.AlterUniqueTogether(
            name='modulorolpermisosusuario',
            unique_together=set([('usuario', 'modulorolpermisos')]),
        ),
        migrations.AlterUniqueTogether(
            name='modulorolpermisos',
            unique_together=set([('modulorol', 'permisos')]),
        ),
        migrations.AlterUniqueTogether(
            name='modulorol',
            unique_together=set([('rol', 'modulo')]),
        ),
    ]
