# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_modulo', '0003_auto_20170119_2228'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modulorolpermisosusuario',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='modulorolpermisosusuario',
            name='modulorolpermisos',
        ),
        migrations.RemoveField(
            model_name='modulorolpermisosusuario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ModuloRolPermisosUsuario',
        ),
    ]
