# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_modulo', '0005_auto_20170120_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='proyectosistema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.ProyectoSistema'),
        ),
    ]
