# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_modulo', '0008_auto_20170120_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='is_padre',
            field=models.IntegerField(default=0),
        ),
    ]
