# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_modulo', '0011_auto_20170130_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='codigo',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
