# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20170223_0851'),
        ('usuario_modulo', '0012_auto_20170212_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='proyectosistema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.ProyectoSistema'),
        ),
    ]
