# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_modulo', '0013_permiso_proyectosistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='codigo',
            field=models.IntegerField(),
        ),
    ]
