# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_modulo', '0014_auto_20170227_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='proyectosistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.ProyectoSistema'),
        ),
    ]
