# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('codigo', models.CharField(max_length=8)),
                ('usr_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_creacion', models.DateTimeField(blank=True, null=True)),
                ('usr_edicion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_edicion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'SISTEMA',
                'managed': True,
            },
        ),
    ]
